整合自定义类附属
SlimefunGuguProject/Addons-Wiki pull request #11
Opened 2022-04-17 06:41 UTC by haiman233

2022-04-17 08:59 UTC, ybw0014 requested changes
目录名称应使用单词小写，中间使用`-`分隔开。  
`slimecustom`缺少`README.md`
末地科技不需要改动

2022-04-17 09:22 UTC, haiman233 commented
好了

2022-04-17 16:48 UTC, ybw0014 requested changes
目录应使用小写单词，中间使用`-`分割，如`slimefun-advancements`
Markdown文件名应使用首字母大写单词，中间使用`-`分割（插件名称除外），如`Install-TranscEndence.md`, `SfMobDrops.md`.

2022-04-22 11:50 UTC, haiman233 commented
awa？markdown文件是什么

2022-04-22 11:51 UTC, haiman233 commented
目录指的是哪个

2022-04-25 00:32 UTC, ybw0014 commented
晚点我改一下

2022-04-25 17:39 UTC, merged