无尽更新
SlimefunGuguProject/Addons-Wiki pull request #18
Opened 2022-06-12 01:25 UTC by JiangQiYan713

补充介绍魔改版特有的材料

2022-06-12 02:42 UTC, ybw0014 requested changes

2022-06-12 02:42 UTC, ybw0014 commented on pages/infinity-expansion/Singularities-changed.md
> +| 锡结果 | 锡锭 | 3000 |
👀

2022-06-12 02:42 UTC, ybw0014 commented on pages/infinity-expansion/Singularities-changed.md
> +| 铜奇点 | 铜锭 | 3000 |
:eyes:

2022-06-12 02:45 UTC, JiangQiYan713 commented on pages/infinity-expansion/Singularities-changed.md
> +| 锡结果 | 锡锭 | 3000 |
啊这啊这 大意了

2022-06-13 06:39 UTC, ybw0014 approved these changes

2022-06-13 06:39 UTC, merged