wiki大更新Part1
SlimefunGuguProject/Addons-Wiki pull request #35
Opened 2023-04-02 06:45 UTC by haiman233

补充了无尽贪婪、动力科技的教程，添加了至尊研究院教程和基因工程的杂交图

2023-04-02 06:52 UTC, haiman233 commented
第一部分内容就是那么多了，清明节的时候搞第二部分
就是那个用链接来贴图片
类似于：https://gzassets.cn/minecraft/plugin/slimefun/wiki/addons/images/dyna-tech/fengxiang1.png
是要在哪里先上传图片吗，还是在images里放图片就行了

2023-04-02 18:29 UTC, ybw0014 commented
> 第一部分内容就是那么多了，清明节的时候搞第二部分 就是那个用链接来贴图片 类似于：[gzassets.cn/minecraft/plugin/slimefun/wiki/addons/images/dyna-tech/fengxiang1.png](https://gzassets.cn/minecraft/plugin/slimefun/wiki/addons/images/dyna-tech/fengxiang1.png) 是要在哪里先上传图片吗，还是在images里放图片就行了

扔images就行

2023-04-03 06:39 UTC, ybw0014 requested changes

2023-04-03 06:39 UTC, ybw0014 commented on pages/dyna-tech/Page1.md
> +**·** 原版所有食物，除了以下物品：
列表前面用 `-` 或者 `*`。

```md
- 1
- 2
```

- 1
- 2

2023-04-03 06:39 UTC, ybw0014 commented on pages/dyna-tech/Page2.md
> +自然生成和割草都有很大的随机性，想要获取指定的种子更是大海捞针.。
```suggestion
自然生成和割草都有很大的随机性，想要获取指定的种子更是大海捞针。

```

2023-04-03 06:39 UTC, ybw0014 commented on pages/infinity-expansion/_sidebar.md
> +	- [部分机器运行机制](./Operating-Mechanism)
缩进需要一致

2023-04-03 06:39 UTC, ybw0014 commented on pages/infinity-expansion/Operating-Mechanism.md
> +作经历了以下过程：
是不是漏了什么

2023-04-03 06:39 UTC, ybw0014 commented on pages/infinity-expansion/Operating-Mechanism.md
> +滤网底座和其他机器不同。别的机器都是定时生产，它却是随机生产。
加段落分割物品

2023-04-03 06:39 UTC, ybw0014 commented on pages/slime-customizer/README.md
> +请在使用本附属前详细地阅读**“使用前声明”**。
加链接

2023-04-05 15:20 UTC, ybw0014 commented
一次性看的东西太多了，以后每个PR只覆盖一个附属

2023-04-06 13:52 UTC, haiman233 commented
ok,等我把sc的教程写完就完成了

2023-04-06 14:49 UTC, haiman233 commented
好，目前新内容已经完成了，周末我会新开个pr来更新wiki

2023-04-07 23:47 UTC, ybw0014 requested changes
看得头疼，既然B站有教程直接放链接就行了

2023-04-07 23:47 UTC, ybw0014 commented on pages/dyna-tech/Page1.md
> +
加几个3级标题，多行分割并不会渲染成多行。
也可以加分割线，不过最好还是用标题，好找。

2023-04-07 23:47 UTC, ybw0014 commented on pages/dyna-tech/Page2.md
> +**·** 将 1 个种子（小麦、甜菜、南瓜、西瓜）转化为种子和对应作物。
列表用 `-` 或 `*`。

2023-04-07 23:47 UTC, ybw0014 commented on pages/dyna-tech/Page2.md
> +
使用分割线进行分割

2023-04-07 23:47 UTC, ybw0014 commented on pages/dyna-tech/Page2.md
> +**·** 若转化的方块是石头，则随机转化为：
列表

2023-04-08 09:49 UTC, haiman233 commented
b站上就这么多教程了，到时候明天周末我自己再检查一遍吧
主要是b站基本上没啥人会点过去看

2023-04-09 22:50 UTC, closed without merging