docs: 为下界乌托邦添加种子数据表
SlimefunGuguProject/Addons-Wiki pull request #46
Opened 2023-10-05 04:15 UTC by Violet-Nonbloosom

2023-10-05 14:11 UTC, ybw0014 requested changes

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +| 沙漠之种 | 16     | 10% | 下界草方块、沙漠结构 | 沙漠 |
```suggestion
| 沙漠之种 | 16 | 10% | 下界草方块、沙漠结构 | 沙漠 |
```

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +| 作物之种 | 2 | 8% | 净化的下界岩（及以上） | 1%       |
```suggestion
| 作物之种 | 2 | 8% | 净化的下界岩（及以上） | 1% |
```

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +# 繁殖
```suggestion
## 繁殖
```

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +|---------|---------|---------|------|------|
---前后应有空格

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +| 种子      | 母本      | 父本      | 繁殖概率 | 克隆概率 |
```suggestion
| 种子 | 母本 | 父本 | 繁殖概率 | 克隆概率 |
```

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +| 灵魂之种    | 腐烂之种    | 净化之种    | 10%  | 20%  |
`|` 前后最多只能有1个空格

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +# 风味
```suggestion
## 风味
```

2023-10-05 14:11 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +| 种子           | 甜   | 酸   | 咸   | 苦   | 鲜   |
该部分要求与上方一致

2023-10-05 15:15 UTC, Violet-Nonbloosom commented
剩下两张表的内容放在一条 commit 里面修改了。

2023-10-05 16:04 UTC, ybw0014 requested changes

2023-10-05 16:04 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +| 怨恨之种 | 0 | 20% | 下界泥土（及以上） |  | 爆炸 | 5%       |
```suggestion
| 怨恨之种 | 0 | 20% | 下界泥土（及以上） |  | 爆炸 | 5% |
```

2023-10-05 16:04 UTC, ybw0014 commented on pages/netheopoiesis/Seed-Database.md
> +## 繁殖
感觉叫培育会更好点

2023-10-05 23:13 UTC, Violet-Nonbloosom commented on pages/netheopoiesis/Seed-Database.md
> +## 繁殖
已按要求修改。

2023-10-06 01:01 UTC, ybw0014 approved these changes

2023-10-06 01:01 UTC, merged