对sc wiki的补充
SlimefunGuguProject/Addons-Wiki pull request #52
Opened 2024-07-01 05:08 UTC by haiman233

2024-07-01 05:09 UTC, haiman233 commented
还有个榨汁机要补充，可以等sc那ok之后在加

2024-07-01 13:06 UTC, ybw0014 requested changes
末尾加上句号。
在英文单词两边加上空格，sc 使用大写 SC。

2024-07-04 15:15 UTC, ybw0014 requested changes

2024-07-04 15:15 UTC, ybw0014 commented on docs/slime-customizer/common/registering.md
> +当你装载 SC 的配置时，请盯好后台显示的错误提示，并依据错误提示修改你的 SC 配置
末尾句号

2024-07-04 15:15 UTC, ybw0014 commented on docs/slime-customizer/config/machines.md
> +小技巧：当你给一个输入物品设置的数量为0时，此时该输入物品不会被机器消耗，但是你必须要将此输入物品放入输入槽才能使机器运行，粘液书和配方里不会显示数量为0的物品，所以你需要在lore里额外描述
末尾句号

2024-07-04 15:15 UTC, ybw0014 commented on docs/slime-customizer/index.md
> +SlimeCustomizer 是一个 Slimefun 附属（后文简称SC），可以让服主只通过配置文件就能创建一个附属，操作简单易懂。
使用全角括号

```suggestion
SlimeCustomizer 是一个 Slimefun 附属（后文简称SC），可以让服主只通过配置文件就能创建一个附属，操作简单易懂。
```

2024-07-04 15:15 UTC, ybw0014 commented on docs/slime-customizer/index.md
> +SlimeCustomizer 相较于 RykenSlimeCustomizer ，限制较大，可自定义范围较小，如果你想编写拥有更多功能的自定义附属，推荐使用 [RykenSlimeCustomizer](https://github.com/SlimefunReloadingProject/RykenSlimeCustomizer)。
英文与标点符号之间不需要空格
```suggestion
SlimeCustomizer 相较于 RykenSlimeCustomizer，限制较大，可自定义范围较小，如果你想编写拥有更多功能的自定义附属，推荐使用 [RykenSlimeCustomizer](https://github.com/SlimefunReloadingProject/RykenSlimeCustomizer)。
```

2024-07-14 08:03 UTC, haiman233 commented
o了

2024-07-14 13:19 UTC, ybw0014 approved these changes

2024-07-14 13:19 UTC, merged